services:
  - type: web
    name: mirchivision
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    dockerfilePath: Dockerfile
    envVars:
      - key: AGMARKNET_KEY
        sync: false
      - key: AGROMARKET_API_URL
        sync: false
